apiVersion: v2
description: A Helm chart for appcatalog CRs and related configmaps and secrets. Used
  by opsctl ensure appcatalogs.
home: https://github.com/giantswarm/appcatalog
name: appcatalog
appVersion:
- - .AppVersion
version:
- - .Version
annotations:
  io.giantswarm.application.team: honeybadger
